
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmutex.h"

/*
* The configuration table for devices
*/

XMutex_Config XMutex_ConfigTable[] =
{
	{
		 XPAR_MUTEX_0_IF_0_DEVICE_ID, 
		 XPAR_MUTEX_0_IF_0_BASEADDR, 
		 XPAR_MUTEX_0_IF_0_NUM_MUTEX, 
		 XPAR_MUTEX_0_IF_0_ENABLE_USER, 
	},
};
