set sitau_apps {
    {{CPU0} {standalone_domain} {Both_CPUs_system} {src/cpu0} {} {}}
    {{CPU1} {ps7_cortex_a0_1} {CPU1_system} {src/cpu1} {{} {SITAU2} {SITAU2/AFE} {SITAU2/AXIL2STREAM} {SITAU2/BCC_BUSSAR} {SITAU2/BEAMFORMER} {SITAU2/CH_EXTRACT} {SITAU2/COMMON} {SITAU2/DATAMOVER} {SITAU2/DYNAMIC_PHASE} {SITAU2/FIFO_CTRL} {SITAU2/FILTRO_FIR} {SITAU2/GTX} {SITAU2/HW_UCI} {SITAU2/PROM_EMI} {SITAU2/PULSER} {SITAU2/SWITCH} {SITAU2/TGC} {SITAU2/UCI} {UI} {UI/ACQ}} {m}}
}
