/*
 * bussar_addr.h
 *
 *  Created on: 26 mar. 2019
 *      Author: Jorge
 */

#ifndef SRC_SITAU2_BCC_BUSSAR_BUSSAR_ADDR_H_
#define SRC_SITAU2_BCC_BUSSAR_BUSSAR_ADDR_H_

//#define DATAMOVER256_BUSSAR_SUBMOD_ADDR	0
#define DATAMOVER032_BUSSAR_SUBMOD_ADDR	1
#define AFE_BUSSAR_SUBMOD_ADDR			2
#define PULSER_BUSSAR_SUBMOD_ADDR		3
#define TGC_BUSSAR_SUBMOD_ADDR			4
#define BEAMFORMER_BUSSAR_SUBMOD_ADDR	5
#define DATAMOVBEAMF_BUSSAR_SUBMOD_ADDR	6
#define MISC_BUSSAR_SUBMOD_ADDR			7
#define SSWITCH032_BUSSAR_SUBMOD_ADDR	8
#define FIFO_CONTROL_SUBMOD_ADDR		9
#define EMI_PROM_SUBMOD_ADDR			10
#define SSWITCH512_BUSSAR_SUBMOD_ADDR	11
#define ADDOPPLER_BUSSAR_SUBMOD_ADDR	12  //Este no está
#define DATAMOVER256_BUSSAR_SUBMOD_ADDR	13
#define SSWITCH256_BUSSAR_SUBMOD_ADDR	14
#define SSWITCHGTX_BUSSAR_SUBMOD_ADDR   15  //Este no está

#define MAX_MINIBASES					8
//#define MAX_MINIBASES					4


//REGISTROS MISCELANEOS

#define MISC_FIL_SHFT_REG		1
#define MISC_GTX_FSM_CTRL_REG	2
#define MISC_NOT_BUSY_IN_REG	3
#define MISC_NOT_BUSY_OR_REG	4
#define MISC_MEM2GTX_SPEED_REG	5
#define MISC_DW_GTX_STS_REG		6
#define MISC_UP_GTX_STS_REG		7
#define MISC_VERSION_DATE_REG	8
#define MISC_PRO_LINK_REG		9
#define MISC_ADDR_CHAIN_REG		10
#define MISC_PS_CONTROL_REG		11  //Mod
#define MISC_PS_TICK_COUNT_REG	12	//Mod
#define MISC_PS_TICK_TARGET_REG 13
#define MISC_PRO_MASK_REG		14

#define MISC_GTX_ADV_CTRL_DN    32
#define MISC_GTX_ADV_CTRL_UP    33

#define MISC_FIL_SHFT_BIT_CE	24
#define MISC_FIL_SHFT_MASK  	0xF

#define MISC_BUSY_BIT_DMVR_32	0
#define MISC_BUSY_BIT_AFES		1
#define MISC_BUSY_BIT_DMVR_256	2
#define MISC_BUSY_BIT_PULSER	3
#define MISC_BUSY_BIT_TGC		4
#define MISC_BUSY_BIT_BFMR		5
#define MISC_BUSY_BIT_DMVR_BFMR 6

#define MISC_PROENA_BIT_DMVR_32		0
#define MISC_PROENA_BIT_AFES		1
#define MISC_PROENA_BIT_DMVR_256	2
#define MISC_PROENA_BIT_PULSER		3
#define MISC_PROENA_BIT_TGC			4
#define MISC_PROENA_BIT_BFMR		5
#define MISC_PROENA_BIT_DMVR_BFMR 	6

#define MISC_GTX_HEADER_CTRL	15
#define MISC_GTX_HEADER_DATA	16



#define MISC_GTX_HEADER_CTRL_VLD_MASK	0x1
#define MISC_GTX_HEADER_CTRL_LST_MASK	0x2
#define MISC_GTX_HEADER_CTRL_ACK_MASK	0x4
#define MISC_GTX_HEADER_CTRL_RDY_MASK	0x8

#define GTX_HEADER_SIZE			8


#endif /* SRC_SITAU2_BCC_BUSSAR_BUSSAR_ADDR_H_ */
