/*
 * mmu_config.c
 *
 *  Created on: 20 de ene. de 2017
 *      Author: csic
 */

#include "mmu_config.h"

#define ONE_MB	(1024*1024)
void config_mmu(u32 start_address,u32 size,u32 atribbutes)
{
	atribbutes&=0x000FFFFC; //OPTIONS MASK
	atribbutes|=0x00000002; //1MB SECTION MASK
	for(u32 section_address=start_address;section_address<(start_address+size);section_address+=ONE_MB)
		Xil_SetTlbAttributes((INTPTR) section_address,atribbutes);
}

void cpu0_net_mmu_config(void)
{
	config_mmu(CPU0_C_START,CPU0_C_SIZE,MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_WR_BACK_WR_ALLOC|MMU_TLB_DOMAIN_MASK);								// RW, WB WA cacheable, no shared
	config_mmu(CPU1_C_START,CPU1_C_SIZE,MMU_TLB_AP_NO_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE); 														// No access, no cacheable, no shared
	config_mmu(CONST_PROD_S_START,ONE_MB,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);				// RW, no cacheable, shared
	config_mmu(HOST2UCI_BUF_START,HOST2UCI_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);	// RW, no cacheable, shared
	config_mmu(UCI2HOST_BUF_START,UCI2HOST_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_READ_ONLY|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);		// RO, no cacheable, shared
	config_mmu(IMAGE_BUF_START,IMAGE_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_READ_ONLY|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);			// RO, no cacheable, shared
	config_mmu(LAST_SHRD_MB_START,ONE_MB,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);				// RW, no cacheable, shared
}
void cpu1_uci_mmu_config_funciona(void)
{
	//config_mmu(CPU0_C_START,CPU0_C_SIZE,MMU_TLB_AP_NO_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE); 														// No access, no cacheable, no shared
	config_mmu(CPU1_C_START,CPU1_C_SIZE,MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_WR_BACK_WR_ALLOC|MMU_TLB_DOMAIN_MASK);								// RW, WB WA cacheable, no shared
	config_mmu(CONST_PROD_S_START,ONE_MB,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);				// RW, no cacheable, shared
	config_mmu(HOST2UCI_BUF_START,HOST2UCI_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_READ_ONLY|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);		// RO, no cacheable, shared
	config_mmu(UCI2HOST_BUF_START,UCI2HOST_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);	// RW, no cacheable, shared
	//config_mmu(IMAGE_BUF_START,IMAGE_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);			// RW, no cacheable, shared
	config_mmu(LAST_SHRD_MB_START,ONE_MB,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);				// RW, no cacheable, shared
}
void cpu1_uci_mmu_config(void)
{
	config_mmu(CPU0_C_START,CPU0_C_SIZE,MMU_TLB_AP_NO_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE); 														// No access, no cacheable, no shared
	config_mmu(CPU1_C_START,CPU1_C_SIZE,MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_WR_BACK_WR_ALLOC|MMU_TLB_DOMAIN_MASK);								// RW, WB WA cacheable, no shared
	config_mmu(CONST_PROD_S_START,ONE_MB,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);				// RW, no cacheable, shared
	config_mmu(HOST2UCI_BUF_START,HOST2UCI_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_READ_ONLY|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);		// RO, no cacheable, shared
	config_mmu(UCI2HOST_BUF_START,UCI2HOST_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);	// RW, no cacheable, shared
	config_mmu(IMAGE_BUF_START,IMAGE_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_NO_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);			// RW, no cacheable, shared
	config_mmu(LAST_SHRD_MB_START,ONE_MB,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);				// RW, no cacheable, shared
}

void cpu0_net_mmu_config_all_cacheable(void)
{
	config_mmu(CPU0_C_START,CPU0_C_SIZE,MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_WR_BACK_WR_ALLOC|MMU_TLB_DOMAIN_MASK);									// RW, WB WA cacheable, no shared
	config_mmu(CPU1_C_START,CPU1_C_SIZE,MMU_TLB_AP_NO_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE); 															// No access, no cacheable, no shared
	config_mmu(CONST_PROD_S_START,ONE_MB,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_WR_THRU_WR_NALLOC|MMU_TLB_DOMAIN_MASK);				// RW, no cacheable, shared
	config_mmu(HOST2UCI_BUF_START,HOST2UCI_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_WR_THRU_WR_NALLOC|MMU_TLB_DOMAIN_MASK);	// RW, no cacheable, shared
	config_mmu(UCI2HOST_BUF_START,UCI2HOST_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_READ_ONLY|MMU_TLB_TEXCB_WR_THRU_WR_NALLOC|MMU_TLB_DOMAIN_MASK);	// RO, no cacheable, shared
	config_mmu(IMAGE_BUF_START,IMAGE_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_READ_ONLY|MMU_TLB_TEXCB_WR_THRU_WR_NALLOC|MMU_TLB_DOMAIN_MASK);			// RO, no cacheable, shared
	config_mmu(LAST_SHRD_MB_START,ONE_MB,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);				// RW, no cacheable, shared
}
void cpu1_uci_mmu_config_all_cacheable(void)
{
	config_mmu(CPU0_C_START,CPU0_C_SIZE,MMU_TLB_AP_NO_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE); 														// No access, no cacheable, no shared
	config_mmu(CPU1_C_START,CPU1_C_SIZE,MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_WR_BACK_WR_ALLOC|MMU_TLB_DOMAIN_MASK);								// RW, WB WA cacheable, no shared
	config_mmu(CONST_PROD_S_START,ONE_MB,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_WR_THRU_WR_NALLOC|MMU_TLB_DOMAIN_MASK);				// RW, no cacheable, shared
	config_mmu(HOST2UCI_BUF_START,HOST2UCI_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_READ_ONLY|MMU_TLB_TEXCB_WR_THRU_WR_NALLOC|MMU_TLB_DOMAIN_MASK);		// RO, no cacheable, shared
	config_mmu(UCI2HOST_BUF_START,UCI2HOST_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_WR_THRU_WR_NALLOC|MMU_TLB_DOMAIN_MASK);	// RW, no cacheable, shared
	config_mmu(IMAGE_BUF_START,IMAGE_BUF_SIZE,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_WR_THRU_WR_NALLOC|MMU_TLB_DOMAIN_MASK);			// RW, no cacheable, shared
	config_mmu(LAST_SHRD_MB_START,ONE_MB,MMU_TLB_SHAREABLE|MMU_TLB_AP_FULL_ACCESS|MMU_TLB_TEXCB_NO_CACHEABLE|MMU_TLB_DOMAIN_MASK);				// RW, no cacheable, shared
}
