
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtmrctr.h"

/*
* The configuration table for devices
*/

XTmrCtr_Config XTmrCtr_ConfigTable[XPAR_XTMRCTR_NUM_INSTANCES] =
{
	{
		XPAR_AXI_TIMER_0_DEVICE_ID,
		XPAR_AXI_TIMER_0_BASEADDR,
		XPAR_AXI_TIMER_0_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_TIMER_1_DEVICE_ID,
		XPAR_AXI_TIMER_1_BASEADDR,
		XPAR_AXI_TIMER_1_CLOCK_FREQ_HZ
	},
	{
		XPAR_AXI_TIMER_2_DEVICE_ID,
		XPAR_AXI_TIMER_2_BASEADDR,
		XPAR_AXI_TIMER_2_CLOCK_FREQ_HZ
	},
	{
		XPAR_TIMESTAMP_TIMER_DEVICE_ID,
		XPAR_TIMESTAMP_TIMER_BASEADDR,
		XPAR_TIMESTAMP_TIMER_CLOCK_FREQ_HZ
	},
	{
		XPAR_TRIGGER_TIMER_DEVICE_ID,
		XPAR_TRIGGER_TIMER_BASEADDR,
		XPAR_TRIGGER_TIMER_CLOCK_FREQ_HZ
	}
};


